const cases = [
 {id:"kemper", name:"Edmund Kemper", alias:"Co-ed Killer", place:"Estados Unidos", period:"1964–1973", victims:"10", sentence:"Prisión de por vida", tags:["victimología","M.O.","perfil","teorías"], accent:"E. K."},
 {id:"dahmer", name:"Jeffrey Dahmer", alias:"Milwaukee Cannibal", place:"Estados Unidos", period:"1978–1991", victims:"17", sentence:"Cadena perpetua", tags:["victimología","M.O.","firma","teorías"], accent:"J. D."},
 {id:"holmes", name:"Henry Howard Holmes", alias:"Dr. Henry Holmes", place:"Estados Unidos", period:"Siglo XIX", victims:"Número discutido", sentence:"Ejecutado", tags:["perfil","fraude","M.O."], accent:"H. H. H."},
 {id:"desalvo", name:"Albert DeSalvo", alias:"El Estrangulador de Boston", place:"Estados Unidos", period:"1962–1964", victims:"Atribución discutida", sentence:"Condenado por otros delitos", tags:["victimología","investigación","M.O."], accent:"A. D."},
 {id:"onoprienko", name:"Anatoli Onoprienko", alias:"La Bestia de Ucrania", place:"Ucrania", period:"1989–1996", victims:"52", sentence:"Cadena perpetua", tags:["M.O.","neutralización","teorías"], accent:"A. O."},
 {id:"ridgway", name:"Gary Leon Ridgway", alias:"Green River Killer", place:"Estados Unidos", period:"1982–2001", victims:"49 confesados/condenados", sentence:"Cadena perpetua", tags:["victimología","M.O.","investigación"], accent:"G. R."},
 {id:"gacy", name:"John Wayne Gacy", alias:"Killer Clown", place:"Estados Unidos", period:"1972–1978", victims:"33", sentence:"Pena de muerte", tags:["victimología","M.O.","investigación"], accent:"J. G."},
 {id:"bpb", name:"Ken Bianchi y Angelo Buono", alias:"Estranguladores de Hillside", place:"Estados Unidos", period:"1977–1978", victims:"10", sentence:"Cadena perpetua", tags:["coautoría","victimología","M.O."], accent:"K. B. / A. B."},
 {id:"little", name:"Samuel Little", alias:"Samuel McDowell Little", place:"Estados Unidos", period:"1970–2005", victims:"93 confesados", sentence:"Cadena perpetua", tags:["victimología","identidad","teorías"], accent:"S. L."}
];

const concepts = [
 ["Modus operandi","Conjunto de conductas y procedimientos utilizados para llevar a cabo el delito. Puede modificarse con la experiencia."],
 ["Firma criminal","Elementos conductuales que exceden lo estrictamente necesario para cometer el delito y pueden presentar una relación con necesidades psicológicas o expresivas del autor."],
 ["Victimología","Estudio de las características de las víctimas y de su relación con el hecho criminal, atendiendo a factores como vulnerabilidad, selección y contexto."],
 ["Periodo de enfriamiento","Intervalo que separa episodios homicidas en la conceptualización del asesinato serial."],
 ["Técnicas de neutralización","Mecanismos mediante los cuales una persona puede justificar, minimizar o racionalizar una conducta desviada."],
 ["Actos de precaución","Conductas dirigidas a reducir las posibilidades de identificación o detención."],
 ["Perfil criminológico","Proceso de análisis de patrones conductuales y características relevantes para orientar la investigación criminal."],
 ["Identidad fracturada","Concepto utilizado en determinados enfoques para describir una construcción identitaria fragmentada; su aplicación depende del marco teórico utilizado."]
];

const details = {
 kemper:{child:"El material aborda su infancia y adolescencia, la relación familiar y el desarrollo temprano de conductas violentas.", career:"El caso recoge una evolución desde delitos cometidos durante la adolescencia hasta una serie de homicidios en la edad adulta.", victimology:"Las víctimas y su relación con el autor se analizan atendiendo a los patrones recogidos en el caso.", mo:"El material diferencia las acciones necesarias para cometer los homicidios de otros comportamientos asociados al caso.", profile:"El informe del caso incorpora un perfil criminológico y diferentes explicaciones teóricas.", theories:"Se presentan varias teorías criminológicas para interpretar su trayectoria."},
 dahmer:{child:"El expediente aborda elementos de su infancia y adolescencia y su evolución posterior.", career:"El caso recoge su trayectoria homicida entre 1978 y 1991.", victimology:"El material incluye un análisis de las víctimas y de los patrones de selección.", mo:"Se describe el procedimiento empleado y se diferencia entre modus operandi y firma.", profile:"El caso incorpora un perfil criminológico.", theories:"Se incluyen distintas teorías criminológicas aplicadas al caso."},
 holmes:{child:"El material incluye información biográfica y de desarrollo temprano.", career:"Se analiza su trayectoria criminal dentro del contexto histórico del caso.", victimology:"Se aborda la selección y relación con las víctimas.", mo:"El expediente describe procedimientos y conductas vinculadas a los delitos.", profile:"El material contiene un apartado específico de perfil criminológico.", theories:"Se presentan interpretaciones criminológicas del caso."},
 desalvo:{child:"El caso incorpora información biográfica previa a los hechos atribuidos.", career:"El material estudia la trayectoria criminal y la investigación del denominado Estrangulador de Boston.", victimology:"Se aborda el conjunto de víctimas atribuidas al caso, cuya autoría histórica presenta elementos discutidos.", mo:"Se analiza el método empleado en los homicidios atribuidos.", profile:"El caso permite diferenciar hechos acreditados judicialmente de atribuciones relacionadas con los homicidios.", theories:"El expediente incorpora elementos de interpretación criminológica."},
 onoprienko:{child:"El expediente desarrolla su infancia y adolescencia.", career:"Se analiza su carrera criminal y la sucesión de homicidios.", victimology:"Se estudian las características y selección de las víctimas.", mo:"El material describe su modus operandi y las formas de evitar la captura.", profile:"Se analiza su comportamiento criminal desde diferentes perspectivas.", theories:"Se incluyen técnicas de neutralización y teorías criminológicas."},
 ridgway:{child:"El material aborda los antecedentes biográficos relevantes.", career:"Se analiza su trayectoria homicida y la investigación que condujo a su identificación.", victimology:"La victimología ocupa un lugar importante en el caso.", mo:"Se estudian los patrones de actuación y ocultación.", profile:"El expediente permite analizar patrones conductuales del autor.", theories:"Se relacionan las conductas con diferentes explicaciones criminológicas."},
 gacy:{child:"El caso recoge información biográfica y de desarrollo.", career:"Se analiza la serie de homicidios y la posterior investigación.", victimology:"El expediente aborda las características de las víctimas.", mo:"Se describe el procedimiento criminal empleado.", profile:"Se pueden estudiar patrones de conducta y organización.", theories:"El caso se interpreta mediante conceptos criminológicos."},
 bpb:{child:"El material aborda infancia, adolescencia y acontecimientos traumáticos relevantes de ambos autores.", career:"Se estudia la actuación conjunta de Ken Bianchi y Angelo Buono.", victimology:"El caso incluye información sobre las víctimas y su selección.", mo:"Se describe cómo actuaban y la dinámica entre ambos.", profile:"El análisis considera la coautoría y los comportamientos de ambos.", theories:"Se pueden relacionar los hechos con diferentes marcos criminológicos."},
 little:{child:"El material incorpora antecedentes biográficos y elementos de su trayectoria.", career:"Se analiza una extensa trayectoria homicida y las confesiones atribuidas al autor.", victimology:"El expediente señala que las víctimas eran mujeres y que muchas se encontraban en situaciones de vulnerabilidad.", mo:"Se estudian los patrones de actuación descritos en el caso.", profile:"El caso incluye un apartado de perfil criminológico.", theories:"El material incorpora la teoría de la identidad fracturada entre sus explicaciones."}
};